-- create a DATABASE hotel
CREATE DATABASE hotel;


--contains info about different hotel room and tariff room type
CREATE TABLE TARIF
(
RTYPE CHAR(2) PRIMARY KEY NOT NULL,
RDESC VARCHAR(20) NOT NULL,
PRICE INT NOT NULL
);

-- insert values into table tariff
INSERT INTO TARIF VALUES (1,'luxury',100000);

-- created a  new table ROOMS
CREATE TABLE ROOMS
(
RNO INT PRIMARY KEY NOT NULL,
RTYPE CHAR(2) NOT NULL,
FLOORNO  INT NOT NULL,
STATUS CHAR(4) NOT NULL,
FOREIGN KEY (RTYPE) REFERENCES TARIF(RTYPE),	


);

